"""Saved, trimmed results pages from each keyless engine (captured live on 2026-09-24), for the self-test's
offline parser checks. Each entry: name -> (content type, body). Generated from real responses; do not edit by hand.
Long strings are split into short literals so no line looks like an embedded blob.
"""

ENGINE_PAGES: dict[str, tuple[str, str]] = {
    'bing-rss': (
        'text/xml; charset=utf-8',
        '<?xml version="1.0" encoding="utf-8" ?><rss version="2.0"><channel><title>Bing: python asyncio tutorial</title><link>htt'
        'p://www.bing.com:80/search?q=python+asyncio+tutorial</link><description>Search results</description><image><url>http://w'
        'ww.bing.com:80/s/a/rsslogo.gif</url><title>python asyncio tutorial</title><link>http://www.bing.com:80/search?q=python+a'
        'syncio+tutorial</link></image><item><title>Welcome to Python.org</title><link>https://www.python.org/</link><description'
        '>Experienced programmers in any other language can pick up Python very quickly, and beginners find the clean syntax and '
        'indentation structure easy to learn. Whet your appetite with our Python 3 overview.</description><pubDate>Thu, 24 Sep 20'
        '26 09:56:00 GMT</pubDate></item><item><title>Download Python | Python.org</title><link>https://www.python.org/downloads/'
        '</link><description>Python was created in the early 1990s by Guido van Rossum at Stichting Mathematisch Centrum in the N'
        'etherlands as a successor of a language called ABC. Guido remains Python’s principal author, although it includes many c'
        'ontributions from others.</description><pubDate>Thu, 24 Sep 2026 17:41:00 GMT</pubDate></item><item><title>Online Python'
        ' - IDE, Editor, Compiler, Interpreter</title><link>https://www.online-python.com/</link><description>Python, which was i'
        'nitially developed by Guido van Rossum and made available to the public in 1991, is currently one of the most widely use'
        'd general-purpose programming languages.</description><pubDate>Wed, 23 Sep 2026 16:10:00 GMT</pubDate></item><item><titl'
        'e>Python (langage) — Wikipédia</title><link>https://fr.wikipedia.org/wiki/Python_(langage)</link><description>Python est'
        " utilisé comme langage de programmation dans l'enseignement secondaire et supérieur, notamment en France 20. Depuis 2013"
        ', il y est enseigné à tous les étudiants de classes préparatoires scientifiques dans le cadre du tronc commun (informati'
        'que commune).</description><pubDate>Wed, 23 Sep 2026 22:08:00 GMT</pubDate></item></channel></rss>'
    ),
    'bing-news': (
        'application/xml; charset=utf-8',
        '<?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xmlns:News="https://www.bing.com/news/search?q=climate+policy&'
        'amp;format=rss"><channel><title>climate policy - BingNews</title><link>https://www.bing.com/news/search?q=climate+policy'
        '&amp;format=rss</link><description>Search results</description><image><url>http://www.bing.com/rsslogo.gif</url><title>c'
        'limate policy</title><link>https://www.bing.com/news/search?q=climate+policy&amp;format=rss</link></image><item><title>C'
        'limate Discourse and Policy Dynamics articles from across Nature Portfolio</title><link>http://www.bing.com/news/apiclic'
        'k.aspx?ref=FexRss&amp;aid=&amp;tid=6ab593d850214b17a5a465a8e1b4ffd0&amp;url=https%3a%2f%2fwww.nature.com%2fsubjects%2fcl'
        'imate-discourse-and-policy-dynamics&amp;c=8589660883676993609&amp;mkt=fr-fr</link><description>Uncover the latest and mo'
        'st impactful research in Climate Discourse and Policy Dynamics. Explore pioneering discoveries, insightful ideas and new'
        ' methods from leading researchers in the field.</description><pubDate>Sun, 20 Sep 2026 17:00:00 GMT</pubDate><News:Sourc'
        'e>Nature</News:Source></item><item><title>These State Elections Could Reshape Climate and Energy Policy</title><link>htt'
        'p://www.bing.com/news/apiclick.aspx?ref=FexRss&amp;aid=&amp;tid=6ab593d850214b17a5a465a8e1b4ffd0&amp;url=https%3a%2f%2fi'
        'nsideclimatenews.org%2fnews%2f17092026%2finside-clean-energy-key-state-elections%2f&amp;c=10912454251712944980&amp;mkt=f'
        'r-fr</link><description>This landscape creates opportunities to advance climate and clean energy policy, said Caroline S'
        'pears, executive director of Climate Cabinet, an advocacy group that focuses on state-level issues and ...</description>'
        '<pubDate>Thu, 17 Sep 2026 06:00:00 GMT</pubDate><News:Source>Inside Climate News</News:Source><News:Image>http://www.bin'
        'g.com/th?id=ONUT.ZVuJhVVB2kRslG-dLigTcg&amp;pid=News</News:Image><News:ImageSize>w={0}&amp;h={1}&amp;c=14</News:ImageSiz'
        'e><News:ImageMaxWidth>300</News:ImageMaxWidth><News:ImageMaxHeight>300</News:ImageMaxHeight></item><item><title>UK energ'
        'y policy faces climate target shortfall amid North Sea licence review</title><link>http://www.bing.com/news/apiclick.asp'
        'x?ref=FexRss&amp;aid=&amp;tid=6ab593d850214b17a5a465a8e1b4ffd0&amp;url=https%3a%2f%2ftradersunion.com%2fnews%2ffinancial'
        '-news%2fshow%2f3451604-uk-energy-policy-climate-shortfall%2f&amp;c=2239103024081553560&amp;mkt=fr-fr</link><description>'
        'The UK risks missing its carbon targets as ministers review North Sea oil and gas licenses and debate support for househ'
        'olds facing energy costs.</description><pubDate>Wed, 23 Sep 2026 04:57:00 GMT</pubDate><News:Source>tradersunion</News:S'
        'ource></item></channel></rss>'
    ),
    'google-news': (
        'application/xml; charset=utf-8',
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/"><c'
        'hannel><generator>NFE/5.0</generator><title>"climate policy" - Google News</title><link>https://news.google.com/search?q'
        '=climate+policy&amp;hl=en-US&amp;gl=US&amp;ceid=US:en</link><language>en-US</language><webMaster>news-webmaster@google.c'
        'om</webMaster><lastBuildDate>Thu, 24 Sep 2026 21:19:20 GMT</lastBuildDate><image><title>Google News</title><url>https://'
        'lh3.googleusercontent.com/-DR60l-K8vnyi99NZovm9HlXyZwQ85GMDxiwJWzoasZYCUrPuUM_P_4Rb7ei03j-0nRs0c4F=w256</url><link>https'
        '://news.google.com/</link><height>256</height><width>256</width></image><description>Google News</description><item><tit'
        'le>Trump dismantled U.S. climate policy. But his war is cutting emissions. - washingtonpost.com</title><link>https://new'
        's.google.com/rss/articles/CBMipgFBVV95cUxOVTdqYndWZnBra1h4YUF2c3A0STJncDEtM0JEMFBJZ3JnaS1DOUhBM1NRSlhnek0zLVRyRGhSa21BSk'
        '05QTJjZHFQTDR3MzBEazV1cGVKLVFUSFptQkRyLWl5NFN6MUZEQ19Ub1QxaXRfeWRvZXB2bmdTZ1ZuOWZ1U3p0RTU5UHlYWDA0dTc5V3VYX21mRGVOU19WTj'
        'R1ZDRxZVl3akF3?oc=5</link><guid isPermaLink="false">CBMipgFBVV95cUxOVTdqYndWZnBra1h4YUF2c3A0STJncDEtM0JEMFBJZ3JnaS1DOUhB'
        'M1NRSlhnek0zLVRyRGhSa21BSk05QTJjZHFQTDR3MzBEazV1cGVKLVFUSFptQkRyLWl5NFN6MUZEQ19Ub1QxaXRfeWRvZXB2bmdTZ1ZuOWZ1U3p0RTU5UHlY'
        'WDA0dTc5V3VYX21mRGVOU19WTjR1ZDRxZVl3akF3</guid><pubDate>Thu, 24 Sep 2026 16:00:00 GMT</pubDate><description>&lt;a href="'
        'https://news.google.com/rss/articles/CBMipgFBVV95cUxOVTdqYndWZnBra1h4YUF2c3A0STJncDEtM0JEMFBJZ3JnaS1DOUhBM1NRSlhnek0zLVR'
        'yRGhSa21BSk05QTJjZHFQTDR3MzBEazV1cGVKLVFUSFptQkRyLWl5NFN6MUZEQ19Ub1QxaXRfeWRvZXB2bmdTZ1ZuOWZ1U3p0RTU5UHlYWDA0dTc5V3VYX21'
        'mRGVOU19WTjR1ZDRxZVl3akF3?oc=5" target="_blank"&gt;Trump dismantled U.S. climate policy. But his war is cutting emission'
        's.&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color="#6f6f6f"&gt;washingtonpost.com&lt;/font&gt;</description><source url="ht'
        'tps://www.washingtonpost.com">washingtonpost.com</source></item><item><title>Commentary: Helene survivor: It’s time to m'
        'ove beyond market-based approaches to climate change - NC Newsline</title><link>https://news.google.com/rss/articles/CBM'
        'itwFBVV95cUxNY1V5R2FBd3RnQy1lSkIzbklpaHM2WTZSWFI4YW82bXJZeGVxSjB5R25MNFF0bGRiM2x6cWNxMmVmMDlKSGpVMFNxRHJOQjNUUzd5RW5sWm9'
        'ZZE5tT1JCbTBDeVpkRE42NG9Rc29mZFpXRzVlSlVraGxTTlhPR2daWnRxVWJacUNIVGJQamRRT2ZjSGtzTFBGNVZGTEZEY1Nrd0otZUc5QjlNdFFTMEtmMnB'
        'KZWZMSVE?oc=5</link><guid isPermaLink="false">CBMitwFBVV95cUxNY1V5R2FBd3RnQy1lSkIzbklpaHM2WTZSWFI4YW82bXJZeGVxSjB5R25MNF'
        'F0bGRiM2x6cWNxMmVmMDlKSGpVMFNxRHJOQjNUUzd5RW5sWm9ZZE5tT1JCbTBDeVpkRE42NG9Rc29mZFpXRzVlSlVraGxTTlhPR2daWnRxVWJacUNIVGJQam'
        'RRT2ZjSGtzTFBGNVZGTEZEY1Nrd0otZUc5QjlNdFFTMEtmMnBKZWZMSVE</guid><pubDate>Thu, 24 Sep 2026 17:35:41 GMT</pubDate><descrip'
        'tion>&lt;a href="https://news.google.com/rss/articles/CBMitwFBVV95cUxNY1V5R2FBd3RnQy1lSkIzbklpaHM2WTZSWFI4YW82bXJZeGVxSj'
        'B5R25MNFF0bGRiM2x6cWNxMmVmMDlKSGpVMFNxRHJOQjNUUzd5RW5sWm9ZZE5tT1JCbTBDeVpkRE42NG9Rc29mZFpXRzVlSlVraGxTTlhPR2daWnRxVWJacU'
        'NIVGJQamRRT2ZjSGtzTFBGNVZGTEZEY1Nrd0otZUc5QjlNdFFTMEtmMnBKZWZMSVE?oc=5" target="_blank"&gt;Commentary: Helene survivor: '
        'It’s time to move beyond market-based approaches to climate change&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color="#6f6f6f"'
        '&gt;NC Newsline&lt;/font&gt;</description><source url="https://ncnewsline.com">NC Newsline</source></item><item><title>E'
        'conomics of demand-side and supply-side climate policies - Brookings</title><link>https://news.google.com/rss/articles/C'
        'BMimAFBVV95cUxNRHUzd284dThNTlY5VzFmSDVqSW55eGg1eHpJeUlMLTR2MV9iYWJmQVhlcmZNMTNFdUI2NHYtdFplYmpLcjhtQWlHVWdjRUhXMmxBNVJWL'
        'U1jREh2Z2R0OGtRQ0w0TG4zZ19PbVM1Qk5ZemVUbUlUN2E1NE5vRkF3cEVhRXFWMG1uZ1o2N1NSekpMTnJSWjR4bQ?oc=5</link><guid isPermaLink="'
        'false">CBMimAFBVV95cUxNRHUzd284dThNTlY5VzFmSDVqSW55eGg1eHpJeUlMLTR2MV9iYWJmQVhlcmZNMTNFdUI2NHYtdFplYmpLcjhtQWlHVWdjRUhXM'
        'mxBNVJWLU1jREh2Z2R0OGtRQ0w0TG4zZ19PbVM1Qk5ZemVUbUlUN2E1NE5vRkF3cEVhRXFWMG1uZ1o2N1NSekpMTnJSWjR4bQ</guid><pubDate>Thu, 24'
        ' Sep 2026 01:00:50 GMT</pubDate><description>&lt;a href="https://news.google.com/rss/articles/CBMimAFBVV95cUxNRHUzd284dT'
        'hNTlY5VzFmSDVqSW55eGg1eHpJeUlMLTR2MV9iYWJmQVhlcmZNMTNFdUI2NHYtdFplYmpLcjhtQWlHVWdjRUhXMmxBNVJWLU1jREh2Z2R0OGtRQ0w0TG4zZ1'
        '9PbVM1Qk5ZemVUbUlUN2E1NE5vRkF3cEVhRXFWMG1uZ1o2N1NSekpMTnJSWjR4bQ?oc=5" target="_blank"&gt;Economics of demand-side and s'
        'upply-side climate policies&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color="#6f6f6f"&gt;Brookings&lt;/font&gt;</description'
        '><source url="https://www.brookings.edu">Brookings</source></item></channel></rss>'
    ),
    'arxiv': (
        'application/atom+xml; charset=utf-8',
        '<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<feed xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:arxiv="http:/'
        '/arxiv.org/schemas/atom" xmlns="http://www.w3.org/2005/Atom">\n  <id>https://arxiv.org/api/czok3h/Lzznp1n/wxg5qdg6ri2Q</i'
        'd>\n  <title>arXiv Query: search_query=all:retrieval AND all:augmented AND all:generation&amp;id_list=&amp;start=0&amp;ma'
        'x_results=5</title>\n  <updated>2026-09-24T21:19:23Z</updated>\n  <link href="https://arxiv.org/api/query?search_query=all'
        ':retrieval+AND+(all:augmented+AND+all:generation)&amp;start=0&amp;max_results=5&amp;id_list=" type="application/atom+xml'
        '"/>\n  <opensearch:itemsPerPage>5</opensearch:itemsPerPage>\n  <opensearch:totalResults>8502</opensearch:totalResults>\n  <'
        'opensearch:startIndex>0</opensearch:startIndex>\n  <entry>\n    <id>http://arxiv.org/abs/2506.06962v3</id>\n    <title>AR-R'
        'AG: Autoregressive Retrieval Augmentation for Image Generation</title>\n    <updated>2025-06-14T00:40:34Z</updated>\n    <'
        'link href="https://arxiv.org/abs/2506.06962v3" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/'
        '2506.06962v3" rel="related" type="application/pdf" title="pdf"/>\n    <summary>We introduce Autoregressive Retrieval Augm'
        'entation (AR-RAG), a novel paradigm that enhances image generation by autoregressively incorporating knearest neighbor r'
        'etrievals at the patch level. Unlike prior methods that perform a single, static retrieval before generation and conditi'
        'on the entire generation on fixed reference images, AR-RAG performs context-aware retrievals at each generation step, us'
        'ing prior-generated patches as queries to retrieve and incorporate the most relevant patch-level visual references, enab'
        'ling the model to respond to evolving generation needs while avoiding limitations (e.g., over-copying, stylistic bias, e'
        'tc.) prevalent in existing methods. To realize AR-RAG, we propose two parallel frameworks: (1) Distribution-Augmentation'
        ' in Decoding (DAiD), a training-free plug-and-use decoding strategy that directly merges the distribution of model-predi'
        'cted patches with the distribution of retrieved patches, and (2) Feature-Augmentation in Decoding (FAiD), a parameter-ef'
        'ficient fine-tuning method that progressively smooths the features of retrieved patches via multi-scale convolution oper'
        'ations and leverages them to augment the image generation process. We validate the effectiveness of AR-RAG on widely ado'
        'pted benchmarks, including Midjourney-30K, GenEval and DPG-Bench, demonstrating significant performance gains over state'
        '-of-the-art image generation models.</summary>\n    <category term="cs.CV" scheme="http://arxiv.org/schemas/atom"/>\n    <'
        'published>2025-06-08T01:33:05Z</published>\n    <arxiv:comment>Image Generation, Retrieval Augmented Generation</arxiv:co'
        'mment>\n    <arxiv:primary_category term="cs.CV"/>\n    <author>\n      <name>Jingyuan Qi</name>\n    </author>\n    <author>'
        '\n      <name>Zhiyang Xu</name>\n    </author>\n    <author>\n      <name>Qifan Wang</name>\n    </author>\n    <author>\n     '
        ' <name>Lifu Huang</name>\n    </author>\n  </entry><entry>\n    <id>http://arxiv.org/abs/2411.18583v1</id>\n    <title>Autom'
        'ated Literature Review Using NLP Techniques and LLM-Based Retrieval-Augmented Generation</title>\n    <updated>2024-11-27'
        'T18:27:07Z</updated>\n    <link href="https://arxiv.org/abs/2411.18583v1" rel="alternate" type="text/html"/>\n    <link hr'
        'ef="https://arxiv.org/pdf/2411.18583v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>This research pr'
        'esents and compares multiple approaches to automate the generation of literature reviews using several Natural Language '
        'Processing (NLP) techniques and retrieval-augmented generation (RAG) with a Large Language Model (LLM). The ever-increas'
        'ing number of research articles provides a huge challenge for manual literature review. It has resulted in an increased '
        'demand for automation. Developing a system capable of automatically generating the literature reviews from only the PDF '
        'files as input is the primary objective of this research work. The effectiveness of several Natural Language Processing '
        '(NLP) strategies, such as the frequency-based method (spaCy), the transformer model (Simple T5), and retrieval-augmented'
        ' generation (RAG) with Large Language Model (GPT-3.5-turbo), is evaluated to meet the primary objective. The SciTLDR dat'
        'aset is chosen for this research experiment and three distinct techniques are utilized to implement three different syst'
        'ems for auto-generating the literature reviews. The ROUGE scores are used for the evaluation of all three systems. Based'
        ' on the evaluation, the Large Language Model GPT-3.5-turbo achieved the highest ROUGE-1 score, 0.364. The transformer mo'
        'del comes in second place and spaCy is at the last position. Finally, a graphical user interface is created for the best'
        ' system based on the large language model.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>'
        '\n    <category term="cs.AI" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="cs.IR" scheme="http://arxiv.org'
        '/schemas/atom"/>\n    <category term="cs.LG" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2024-11-27T18:27:07Z'
        '</published>\n    <arxiv:comment>Key Words : T5, SpaCy, Large Language Model, GPT, ROUGE, Literature Review, Natural Lang'
        'uage Processing, Retrieval-augmented generation</arxiv:comment>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n'
        '      <name>Nurshat Fateh Ali</name>\n    </author>\n    <author>\n      <name>Md. Mahdi Mohtasim</name>\n    </author>\n    '
        '<author>\n      <name>Shakil Mosharrof</name>\n    </author>\n    <author>\n      <name>T. Gopi Krishna</name>\n    </author>'
        '\n  </entry>\n</feed>\n'
    ),
    'bing-html': (
        'text/html; charset=utf-8',
        '<!DOCTYPE html><html lang="en"><head><title>python asyncio tutorial - Search</title></head><body><ol id="b_results"><li '
        'class="b_algo" data-id="" iid="SERP.5351"><div class="b_tpcn"><a class="tilk" aria-label="python.org" redirecturl="" tab'
        'index="-1" target="_blank" href="https://www.bing.com/ck/a?!&amp;&amp;p=ad20a3f5531db573277ef1195c94db45f09713fff420a522'
        '52908e3065b98bcbJmltdHM9MTc5MDIwODAwMA&amp;ptn=3&amp;ver=2&amp;hsh=4&amp;fclid=0165548e-5e09-6b08-1523-43505f456ab7&amp;'
        'u=a1aHR0cHM6Ly93d3cucHl0aG9uLm9yZy8&amp;ntb=1" h="ID=SERP,5131.1"><div class="tpic"><div class="wr_fav" data-priority="2'
        '"><div class="cico siteicon" style="width:32px;height:32px;"><div class="rms_iac" style="height:32px;line-height:32px;wi'
        'dth:32px;" data-height="32" data-width="32" data-alt="Global web icon" data-class="rms_img" data-src="https://th.bing.co'
        'm/th/id/ODLS.A2450BEC-5595-40BA-9F13-D9EC6AB74B9F?w=32&amp;h=32&amp;qlt=90&amp;pcl=fffffa&amp;o=6&amp;pid=1.2"></div></d'
        'iv></div></div><div class="tptxt"><div class="tptt">python.org</div><div class="tpmeta"><div class="b_attribution" tabin'
        'dex="-1"><cite>https://www.python.org</cite></div></div></div></a></div><h2 class=""><a target="_blank" href="https://ww'
        'w.bing.com/ck/a?!&amp;&amp;p=ad20a3f5531db573277ef1195c94db45f09713fff420a52252908e3065b98bcbJmltdHM9MTc5MDIwODAwMA&amp;'
        'ptn=3&amp;ver=2&amp;hsh=4&amp;fclid=0165548e-5e09-6b08-1523-43505f456ab7&amp;u=a1aHR0cHM6Ly93d3cucHl0aG9uLm9yZy8&amp;ntb'
        '=1" h="ID=SERP,5131.2">Welcome to <strong>Python</strong>.org</a></h2><div class="b_caption"><p class="b_lineclamp2" dat'
        'a-rslinkclamp-iid="">Experienced programmers in any other language can pick up Python very quickly, and beginners find t'
        'he clean syntax and …<a class="b_algoReadMore" target="_blank" href="https://www.bing.com/ck/a?!&amp;&amp;p=ad20a3f5531d'
        'b573277ef1195c94db45f09713fff420a52252908e3065b98bcbJmltdHM9MTc5MDIwODAwMA&amp;ptn=3&amp;ver=2&amp;hsh=4&amp;fclid=01655'
        '48e-5e09-6b08-1523-43505f456ab7&amp;u=a1aHR0cHM6Ly93d3cucHl0aG9uLm9yZy8&amp;ntb=1" h="ID=SERP,5131.3">Read more</a></p><'
        '/div><div elementtiming="frp.MiddleOfPage" aria-hidden="true" style="pointer-events:none;margin-top:-1px;height:1px;widt'
        'h:1px;font-size:1px;position:absolute;top:0;right:0;" tabindex="-1"> &nbsp; </div></li><li class="b_algo" data-id="" iid'
        '="SERP.5352"><div class="b_tpcn"><a class="tilk" aria-label="python.org" redirecturl="" tabindex="-1" target="_blank" hr'
        'ef="https://www.bing.com/ck/a?!&amp;&amp;p=12b5f9d5edf0c2cf9e861dd27af8c42808178048a2808fa1acc2f3743c8c18cfJmltdHM9MTc5M'
        'DIwODAwMA&amp;ptn=3&amp;ver=2&amp;hsh=4&amp;fclid=0165548e-5e09-6b08-1523-43505f456ab7&amp;u=a1aHR0cHM6Ly93d3cucHl0aG9uL'
        'm9yZy9kb3dubG9hZHMv&amp;ntb=1" h="ID=SERP,5147.1"><div class="tpic"><div class="wr_fav" data-priority="2"><div class="ci'
        'co siteicon" style="width:32px;height:32px;"><div class="rms_iac" style="height:32px;line-height:32px;width:32px;" data-'
        'height="32" data-width="32" data-alt="Global web icon" data-class="rms_img" data-src="https://th.bing.com/th/id/ODLS.A24'
        '50BEC-5595-40BA-9F13-D9EC6AB74B9F?w=32&amp;h=32&amp;qlt=91&amp;pcl=fffffa&amp;o=6&amp;pid=1.2"></div></div></div></div><'
        'div class="tptxt"><div class="tptt">python.org</div><div class="tpmeta"><div class="b_attribution" tabindex="-1"><cite>h'
        'ttps://www.python.org › downloads</cite></div></div></div></a></div><h2 class=""><a target="_blank" href="https://www.bi'
        'ng.com/ck/a?!&amp;&amp;p=12b5f9d5edf0c2cf9e861dd27af8c42808178048a2808fa1acc2f3743c8c18cfJmltdHM9MTc5MDIwODAwMA&amp;ptn='
        '3&amp;ver=2&amp;hsh=4&amp;fclid=0165548e-5e09-6b08-1523-43505f456ab7&amp;u=a1aHR0cHM6Ly93d3cucHl0aG9uLm9yZy9kb3dubG9hZHM'
        'v&amp;ntb=1" h="ID=SERP,5147.2">Download <strong>Python</strong> | <strong>Python</strong>.org</a></h2><div class="b_cap'
        'tion"><p class="b_lineclamp2" data-rslinkclamp-iid="">Python was created in the early 1990s by Guido van Rossum at Stich'
        'ting Mathematisch Centrum in the Netherlands as a successor …</p></div></li><li class="b_algo" data-id="" iid="SERP.5353'
        '"><div class="b_tpcn"><a class="tilk" aria-label="online-python.com" redirecturl="" tabindex="-1" target="_blank" href="'
        'https://www.bing.com/ck/a?!&amp;&amp;p=c3882f25bf1041353622987c2718ec7f1f75f323ec78f86e88c1744fcf1ffdceJmltdHM9MTc5MDIwO'
        'DAwMA&amp;ptn=3&amp;ver=2&amp;hsh=4&amp;fclid=0165548e-5e09-6b08-1523-43505f456ab7&amp;u=a1aHR0cHM6Ly93d3cub25saW5lLXB5d'
        'Ghvbi5jb20v&amp;ntb=1" h="ID=SERP,5162.1"><div class="tpic"><div class="wr_fav" data-priority="2"><div class="cico sitei'
        'con" style="width:32px;height:32px;"><div class="rms_iac" style="height:32px;line-height:32px;width:32px;" data-height="'
        '32" data-width="32" data-alt="Global web icon" data-class="rms_img" data-src="https://th.bing.com/th/id/ODLS.A2450BEC-55'
        '95-40BA-9F13-D9EC6AB74B9F?w=32&amp;h=32&amp;qlt=92&amp;pcl=fffffa&amp;o=6&amp;pid=1.2"></div></div></div></div><div clas'
        's="tptxt"><div class="tptt">online-python.com</div><div class="tpmeta"><div class="b_attribution" tabindex="-1"><cite>ht'
        'tps://www.online-python.com</cite></div></div></div></a></div><h2 class=""><a target="_blank" href="https://www.bing.com'
        '/ck/a?!&amp;&amp;p=c3882f25bf1041353622987c2718ec7f1f75f323ec78f86e88c1744fcf1ffdceJmltdHM9MTc5MDIwODAwMA&amp;ptn=3&amp;'
        'ver=2&amp;hsh=4&amp;fclid=0165548e-5e09-6b08-1523-43505f456ab7&amp;u=a1aHR0cHM6Ly93d3cub25saW5lLXB5dGhvbi5jb20v&amp;ntb='
        '1" h="ID=SERP,5162.2">Online <strong>Python</strong> - IDE, Editor, Compiler, Interpreter</a></h2><div class="b_caption"'
        '><p class="b_lineclamp2" data-rslinkclamp-iid="">Python, which was initially developed by Guido van Rossum and made avai'
        'lable to the public in 1991, is currently one of the most …</p></div></li></ol></body></html>'
    ),
    'ddg-html': (
        'text/html; charset=UTF-8',
        '<!DOCTYPE html><html><head><title>python asyncio tutorial at DuckDuckGo</title></head><body><div class="serp__results"><'
        'div id="links" class="results"><div class="result results_links results_links_deep result--ad ">\n<div class="links_main '
        'links_deep result__body"> <!-- This is the visible part -->\n<h2 class="result__title">\n<a rel="nofollow" class="result__'
        'a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fduckduckgo.com%2Fy.js%3Fad_domain%3Dudemy.com%26ad_provider%3Dbingv7aa%2'
        '6ad_type%3Dtxad%26click_metadata%3Dj_p0Wk4%252DvhT%252Dbc4jhDBfW7UogYVS%252D2WRoAcex5MC0jVyPBh4dkY66cGve032QZ2Kq1zLYw8os'
        'Qx5uqEQD6LRXv%252DVU7nwlCKEJAyU5VXxOG3MjrnHi%252DafWDJwJKgeUJz4XCbmxIbgM_2sMEs3VPMxDNUE4mxauxedlfcmde_GrGA.JBgx_AFysqxRs'
        'oE8waD66Q%26rut%3D2940987ae6f041728af7c928a5e3394bf4d17380e21e2f74caddd4846c0d01b0%26u3%3Dhttps%253A%252F%252Fwww.bing.c'
        'om%252Faclick%253Fld%253De8Xc0k2fMhII_5CCzxq1fqWDVUCUzTqUueJYAkS1sb6somnyLIXZO2sUhbSN4OlL6_szwfzCcGKh%252DN5v3njMyMQTrN%'
        '252D6x0sa4_X04B7Ivwj1U%252DBKpFzx%252DZYiXTq5GTyvpeFp48DOn5J%252DMbC4PdBmImrervzn5nwDYeWh1U2unsXce%252D46BZtqddimy79_sHl'
        'ppDd_3sbuCN3s7DmPblkCwyjCGOPN4%2526u%253DaHR0cHMlM2ElMmYlMmZ3d3cudWRlbXkuY29tJTJmY291cnNlJTJmc3VwZXJjaGFyZ2VkLXdlYi1zY3J'
        'hcGluZy13aXRoLWFzeW5jaW8tYW5kLXB5dGhvbiUyZiUzZnV0bV9jYW1wYWlnbiUzZEJHLVNlYXJjaF9EU0FfQWxwaGFfUHJvZl9sYS5FTl9jYy5ST1ctRW5'
        'nbGlzaCUyNnV0bV9zb3VyY2UlM2RiaW5nJTI2dXRtX21lZGl1bSUzZHBhaWQtc2VhcmNoJTI2cG9ydGZvbGlvJTNkQmluZy1ST1ctRW5nbGlzaCUyNnV0bV9'
        'hdWRpZW5jZSUzZG14JTI2dXRtX3RhY3RpYyUzZG5iJTI2dXRtX3Rlcm0lM2RfLl9hZ18xMzE3MjE3MzE4NjQ5NjA0Xy5fYWRfXy5fa3dfRGF0YSUyNTIwU2N'
        'pZW5jZSUyNnV0bV9jb250ZW50JTNkcyUyNmZ1bm5lbCUzZCUyNnRlc3QlM2QlMjZ1dG1fY2FtcGFpZ25faWQlM2Q2Mzg1OTYyMjglMjZtc2Nsa2lkJTNkMDA'
        '3YjBjZDQ5ZTIzMTFiMWJmZjQ2NjYxMGQ5NTZhYmU%2526rlid%253D007b0cd49e2311b1bff466610d956abe%26vqd%3D4%2D283975668150798673140'
        '011112122559513587%26iurl%3D%257B1%257DIG%253D99A414F183D94F13B477C22D7F80954B%2526CID%253D04A4773AF23B64113EA060E4F34C6'
        '5B6%2526ID%253DDevEx%252C5037.1&amp;rut=bd7f26667fc3d46fb7c30fe5476bb7988b7a47f9ef61c76cd2d52c2459dd720a">Python Asyncio'
        ' Tutorial - Learn Asynchronous Web Scraping with Python</a>\n<div class="result__badge-wrap">\n<button class="badge--ad">A'
        'd</button>\n<div class="badge--ad__tooltip-wrap">\n<div class="tooltip tooltip--right">\n<div class="tooltip__triangle-oute'
        'r"></div>\n<div class="tooltip__triangle-inner"></div>\nViewing ads is privacy protected by DuckDuckGo. Ad clicks are mana'
        'ged by Microsoft\'s ad network (<a href="https://duckduckgo.com/duckduckgo-help-pages/company/ads-by-microsoft-on-duckduc'
        'kgo-private-search" class="tooltip-link">more info</a>).\n</div>\n</div>\n</div>\n</h2>\n<div class="result__extras">\n<div cl'
        'ass="result__extras__url">\n<!-- Disable Ad Favicon\n<span class="result__icon">\n<a rel="nofollow" class="result__icon__im'
        'g" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fduckduckgo.com%2Fy.js%3Fad_domain%3Dudemy.com%26ad_provider%3Dbingv7aa%2'
        '6ad_type%3Dtxad%26click_metadata%3Dj_p0Wk4%252DvhT%252Dbc4jhDBfW7UogYVS%252D2WRoAcex5MC0jVyPBh4dkY66cGve032QZ2Kq1zLYw8os'
        'Qx5uqEQD6LRXv%252DVU7nwlCKEJAyU5VXxOG3MjrnHi%252DafWDJwJKgeUJz4XCbmxIbgM_2sMEs3VPMxDNUE4mxauxedlfcmde_GrGA.JBgx_AFysqxRs'
        'oE8waD66Q%26rut%3D2940987ae6f041728af7c928a5e3394bf4d17380e21e2f74caddd4846c0d01b0%26u3%3Dhttps%253A%252F%252Fwww.bing.c'
        'om%252Faclick%253Fld%253De8Xc0k2fMhII_5CCzxq1fqWDVUCUzTqUueJYAkS1sb6somnyLIXZO2sUhbSN4OlL6_szwfzCcGKh%252DN5v3njMyMQTrN%'
        '252D6x0sa4_X04B7Ivwj1U%252DBKpFzx%252DZYiXTq5GTyvpeFp48DOn5J%252DMbC4PdBmImrervzn5nwDYeWh1U2unsXce%252D46BZtqddimy79_sHl'
        'ppDd_3sbuCN3s7DmPblkCwyjCGOPN4%2526u%253DaHR0cHMlM2ElMmYlMmZ3d3cudWRlbXkuY29tJTJmY291cnNlJTJmc3VwZXJjaGFyZ2VkLXdlYi1zY3J'
        'hcGluZy13aXRoLWFzeW5jaW8tYW5kLXB5dGhvbiUyZiUzZnV0bV9jYW1wYWlnbiUzZEJHLVNlYXJjaF9EU0FfQWxwaGFfUHJvZl9sYS5FTl9jYy5ST1ctRW5'
        'nbGlzaCUyNnV0bV9zb3VyY2UlM2RiaW5nJTI2dXRtX21lZGl1bSUzZHBhaWQtc2VhcmNoJTI2cG9ydGZvbGlvJTNkQmluZy1ST1ctRW5nbGlzaCUyNnV0bV9'
        'hdWRpZW5jZSUzZG14JTI2dXRtX3RhY3RpYyUzZG5iJTI2dXRtX3Rlcm0lM2RfLl9hZ18xMzE3MjE3MzE4NjQ5NjA0Xy5fYWRfXy5fa3dfRGF0YSUyNTIwU2N'
        'pZW5jZSUyNnV0bV9jb250ZW50JTNkcyUyNmZ1bm5lbCUzZCUyNnRlc3QlM2QlMjZ1dG1fY2FtcGFpZ25faWQlM2Q2Mzg1OTYyMjglMjZtc2Nsa2lkJTNkMDA'
        '3YjBjZDQ5ZTIzMTFiMWJmZjQ2NjYxMGQ5NTZhYmU%2526rlid%253D007b0cd49e2311b1bff466610d956abe%26vqd%3D4%2D283975668150798673140'
        '011112122559513587%26iurl%3D%257B1%257DIG%253D99A414F183D94F13B477C22D7F80954B%2526CID%253D04A4773AF23B64113EA060E4F34C6'
        '5B6%2526ID%253DDevEx%252C5037.1&amp;rut=bd7f26667fc3d46fb7c30fe5476bb7988b7a47f9ef61c76cd2d52c2459dd720a">\n<img width="1'
        '6" height="16" alt="" src="//external-content.duckduckgo.com/ip3/.ico" name="i15" />\n</a>\n</span>\n-->\n<a class="result__'
        'url" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fduckduckgo.com%2Fy.js%3Fad_domain%3Dudemy.com%26ad_provider%3Dbingv7aa'
        '%26ad_type%3Dtxad%26click_metadata%3Dj_p0Wk4%252DvhT%252Dbc4jhDBfW7UogYVS%252D2WRoAcex5MC0jVyPBh4dkY66cGve032QZ2Kq1zLYw8'
        'osQx5uqEQD6LRXv%252DVU7nwlCKEJAyU5VXxOG3MjrnHi%252DafWDJwJKgeUJz4XCbmxIbgM_2sMEs3VPMxDNUE4mxauxedlfcmde_GrGA.JBgx_AFysqx'
        'RsoE8waD66Q%26rut%3D2940987ae6f041728af7c928a5e3394bf4d17380e21e2f74caddd4846c0d01b0%26u3%3Dhttps%253A%252F%252Fwww.bing'
        '.com%252Faclick%253Fld%253De8Xc0k2fMhII_5CCzxq1fqWDVUCUzTqUueJYAkS1sb6somnyLIXZO2sUhbSN4OlL6_szwfzCcGKh%252DN5v3njMyMQTr'
        'N%252D6x0sa4_X04B7Ivwj1U%252DBKpFzx%252DZYiXTq5GTyvpeFp48DOn5J%252DMbC4PdBmImrervzn5nwDYeWh1U2unsXce%252D46BZtqddimy79_s'
        'HlppDd_3sbuCN3s7DmPblkCwyjCGOPN4%2526u%253DaHR0cHMlM2ElMmYlMmZ3d3cudWRlbXkuY29tJTJmY291cnNlJTJmc3VwZXJjaGFyZ2VkLXdlYi1zY'
        '3JhcGluZy13aXRoLWFzeW5jaW8tYW5kLXB5dGhvbiUyZiUzZnV0bV9jYW1wYWlnbiUzZEJHLVNlYXJjaF9EU0FfQWxwaGFfUHJvZl9sYS5FTl9jYy5ST1ctR'
        'W5nbGlzaCUyNnV0bV9zb3VyY2UlM2RiaW5nJTI2dXRtX21lZGl1bSUzZHBhaWQtc2VhcmNoJTI2cG9ydGZvbGlvJTNkQmluZy1ST1ctRW5nbGlzaCUyNnV0b'
        'V9hdWRpZW5jZSUzZG14JTI2dXRtX3RhY3RpYyUzZG5iJTI2dXRtX3Rlcm0lM2RfLl9hZ18xMzE3MjE3MzE4NjQ5NjA0Xy5fYWRfXy5fa3dfRGF0YSUyNTIwU'
        '2NpZW5jZSUyNnV0bV9jb250ZW50JTNkcyUyNmZ1bm5lbCUzZCUyNnRlc3QlM2QlMjZ1dG1fY2FtcGFpZ25faWQlM2Q2Mzg1OTYyMjglMjZtc2Nsa2lkJTNkM'
        'DA3YjBjZDQ5ZTIzMTFiMWJmZjQ2NjYxMGQ5NTZhYmU%2526rlid%253D007b0cd49e2311b1bff466610d956abe%26vqd%3D4%2D2839756681507986731'
        '40011112122559513587%26iurl%3D%257B1%257DIG%253D99A414F183D94F13B477C22D7F80954B%2526CID%253D04A4773AF23B64113EA060E4F34'
        'C65B6%2526ID%253DDevEx%252C5037.1&amp;rut=bd7f26667fc3d46fb7c30fe5476bb7988b7a47f9ef61c76cd2d52c2459dd720a">udemy.com</a'
        '>\n</div>\n</div>\n<a class="result__snippet" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fduckduckgo.com%2Fy.js%3Fad_domai'
        'n%3Dudemy.com%26ad_provider%3Dbingv7aa%26ad_type%3Dtxad%26click_metadata%3Dj_p0Wk4%252DvhT%252Dbc4jhDBfW7UogYVS%252D2WRo'
        'Acex5MC0jVyPBh4dkY66cGve032QZ2Kq1zLYw8osQx5uqEQD6LRXv%252DVU7nwlCKEJAyU5VXxOG3MjrnHi%252DafWDJwJKgeUJz4XCbmxIbgM_2sMEs3V'
        'PMxDNUE4mxauxedlfcmde_GrGA.JBgx_AFysqxRsoE8waD66Q%26rut%3D2940987ae6f041728af7c928a5e3394bf4d17380e21e2f74caddd4846c0d01'
        'b0%26u3%3Dhttps%253A%252F%252Fwww.bing.com%252Faclick%253Fld%253De8Xc0k2fMhII_5CCzxq1fqWDVUCUzTqUueJYAkS1sb6somnyLIXZO2s'
        'UhbSN4OlL6_szwfzCcGKh%252DN5v3njMyMQTrN%252D6x0sa4_X04B7Ivwj1U%252DBKpFzx%252DZYiXTq5GTyvpeFp48DOn5J%252DMbC4PdBmImrervz'
        'n5nwDYeWh1U2unsXce%252D46BZtqddimy79_sHlppDd_3sbuCN3s7DmPblkCwyjCGOPN4%2526u%253DaHR0cHMlM2ElMmYlMmZ3d3cudWRlbXkuY29tJTJ'
        'mY291cnNlJTJmc3VwZXJjaGFyZ2VkLXdlYi1zY3JhcGluZy13aXRoLWFzeW5jaW8tYW5kLXB5dGhvbiUyZiUzZnV0bV9jYW1wYWlnbiUzZEJHLVNlYXJjaF9'
        'EU0FfQWxwaGFfUHJvZl9sYS5FTl9jYy5ST1ctRW5nbGlzaCUyNnV0bV9zb3VyY2UlM2RiaW5nJTI2dXRtX21lZGl1bSUzZHBhaWQtc2VhcmNoJTI2cG9ydGZ'
        'vbGlvJTNkQmluZy1ST1ctRW5nbGlzaCUyNnV0bV9hdWRpZW5jZSUzZG14JTI2dXRtX3RhY3RpYyUzZG5iJTI2dXRtX3Rlcm0lM2RfLl9hZ18xMzE3MjE3MzE'
        '4NjQ5NjA0Xy5fYWRfXy5fa3dfRGF0YSUyNTIwU2NpZW5jZSUyNnV0bV9jb250ZW50JTNkcyUyNmZ1bm5lbCUzZCUyNnRlc3QlM2QlMjZ1dG1fY2FtcGFpZ25'
        'faWQlM2Q2Mzg1OTYyMjglMjZtc2Nsa2lkJTNkMDA3YjBjZDQ5ZTIzMTFiMWJmZjQ2NjYxMGQ5NTZhYmU%2526rlid%253D007b0cd49e2311b1bff466610d'
        '956abe%26vqd%3D4%2D283975668150798673140011112122559513587%26iurl%3D%257B1%257DIG%253D99A414F183D94F13B477C22D7F80954B%2'
        '526CID%253D04A4773AF23B64113EA060E4F34C65B6%2526ID%253DDevEx%252C5037.1&amp;rut=bd7f26667fc3d46fb7c30fe5476bb7988b7a47f9'
        'ef61c76cd2d52c2459dd720a">Master Data Science and become a pro. Start today and improve your skills. Find the right inst'
        'ructor for you. Choose from many topics, skill levels, and languages.</a>\n<div class="clear"></div>\n</div>\n</div>\n<div c'
        'lass="result results_links results_links_deep web-result ">\n<div class="links_main links_deep result__body"> <!-- This i'
        's the visible part -->\n<h2 class="result__title">\n<a rel="nofollow" class="result__a" href="//duckduckgo.com/l/?uddg=htt'
        'ps%3A%2F%2Frealpython.com%2Fasync%2Dio%2Dpython%2F&amp;rut=3f1810d12af587f4db70c3cfee586ef362febe0b6f16adb20db167bb14516'
        'cd3">Python\'s asyncio: A Hands-On Walkthrough - Real Python</a>\n</h2>\n<div class="result__extras">\n<div class="result__e'
        'xtras__url">\n<span class="result__icon">\n<a rel="nofollow" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Frealpython.com%2'
        'Fasync%2Dio%2Dpython%2F&amp;rut=3f1810d12af587f4db70c3cfee586ef362febe0b6f16adb20db167bb14516cd3">\n<img class="result__i'
        'con__img" width="16" height="16" alt="" src="//external-content.duckduckgo.com/ip3/realpython.com.ico" name="i15">\n</a>\n'
        '</span>\n<a class="result__url" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Frealpython.com%2Fasync%2Dio%2Dpython%2F&amp;'
        'rut=3f1810d12af587f4db70c3cfee586ef362febe0b6f16adb20db167bb14516cd3">\nrealpython.com/async-io-python/\n</a>\n<span>&nbsp;'
        ' &nbsp; 2025-07-30T00:00:00.0000000</span>\n</div>\n</div>\n<a class="result__snippet" href="//duckduckgo.com/l/?uddg=https'
        '%3A%2F%2Frealpython.com%2Fasync%2Dio%2Dpython%2F&amp;rut=3f1810d12af587f4db70c3cfee586ef362febe0b6f16adb20db167bb14516cd'
        '3"><b>Python\'s</b> <b>asyncio</b> library enables you to write concurrent code using the async and await keywords. The c'
        'ore building blocks of <b>async</b> <b>I/O</b> in <b>Python</b> are awaitable objects—most often coroutines—that an even'
        't loop schedules and executes asynchronously. This programming model lets you efficiently manage multiple I/O-bound task'
        's within a single thread of execution. In this <b>tutorial</b>, you\'ll ...</a>\n<div class="clear"></div>\n</div>\n</div>\n<'
        'div class="result results_links results_links_deep web-result ">\n<div class="links_main links_deep result__body"> <!-- T'
        'his is the visible part -->\n<h2 class="result__title">\n<a rel="nofollow" class="result__a" href="//duckduckgo.com/l/?udd'
        'g=https%3A%2F%2Fwww.geeksforgeeks.org%2Fpython%2Fasyncio%2Din%2Dpython%2F&amp;rut=09c2e9caf0f59f9e8b117f5bd998310aac9ccd'
        '4fe7faf36aa5190d48192ea381">asyncio in Python - GeeksforGeeks</a>\n</h2>\n<div class="result__extras">\n<div class="result_'
        '_extras__url">\n<span class="result__icon">\n<a rel="nofollow" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fwww.geeksforge'
        'eks.org%2Fpython%2Fasyncio%2Din%2Dpython%2F&amp;rut=09c2e9caf0f59f9e8b117f5bd998310aac9ccd4fe7faf36aa5190d48192ea381">\n<'
        'img class="result__icon__img" width="16" height="16" alt="" src="//external-content.duckduckgo.com/ip3/www.geeksforgeeks'
        '.org.ico" name="i15">\n</a>\n</span>\n<a class="result__url" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fwww.geeksforgeeks'
        '.org%2Fpython%2Fasyncio%2Din%2Dpython%2F&amp;rut=09c2e9caf0f59f9e8b117f5bd998310aac9ccd4fe7faf36aa5190d48192ea381">\nwww.'
        'geeksforgeeks.org/python/asyncio-in-python/\n</a>\n<span>&nbsp; &nbsp; 2025-07-23T00:00:00.0000000</span>\n</div>\n</div>\n<a'
        ' class="result__snippet" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fwww.geeksforgeeks.org%2Fpython%2Fasyncio%2Din%2Dpy'
        'thon%2F&amp;rut=09c2e9caf0f59f9e8b117f5bd998310aac9ccd4fe7faf36aa5190d48192ea381"><b>Asyncio</b> is used as a foundation'
        ' for multiple <b>Python</b> asynchronous frameworks that provide high-performance network and web servers, database conn'
        'ection libraries, distributed task queues, etc Asynchronous Programming with <b>Asyncio</b> in <b>Python</b> In the exam'
        'ple below, we\'ll create a function and make it asynchronous using the async keyword.</a>\n<div class="clear"></div>\n</div'
        '>\n</div>\n<div class="result results_links results_links_deep web-result ">\n<div class="links_main links_deep result__bod'
        'y"> <!-- This is the visible part -->\n<h2 class="result__title">\n<a rel="nofollow" class="result__a" href="//duckduckgo.'
        'com/l/?uddg=https%3A%2F%2Fcodesamplez.com%2Fprogramming%2Fpython%2Dasyncio%2Dtutorial&amp;rut=305613caa08d4cac63353ad758'
        '01512996890191db250fcccc6d2ce606f0e856">Python AsyncIO Tutorial: A Comprehensive Guide To Async Python</a>\n</h2>\n<div cl'
        'ass="result__extras">\n<div class="result__extras__url">\n<span class="result__icon">\n<a rel="nofollow" href="//duckduckgo'
        '.com/l/?uddg=https%3A%2F%2Fcodesamplez.com%2Fprogramming%2Fpython%2Dasyncio%2Dtutorial&amp;rut=305613caa08d4cac63353ad75'
        '801512996890191db250fcccc6d2ce606f0e856">\n<img class="result__icon__img" width="16" height="16" alt="" src="//external-c'
        'ontent.duckduckgo.com/ip3/codesamplez.com.ico" name="i15">\n</a>\n</span>\n<a class="result__url" href="//duckduckgo.com/l/'
        '?uddg=https%3A%2F%2Fcodesamplez.com%2Fprogramming%2Fpython%2Dasyncio%2Dtutorial&amp;rut=305613caa08d4cac63353ad758015129'
        '96890191db250fcccc6d2ce606f0e856">\ncodesamplez.com/programming/python-asyncio-tutorial\n</a>\n<span>&nbsp; &nbsp; 2025-02-'
        '10T00:00:00.0000000</span>\n</div>\n</div>\n<a class="result__snippet" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fcodesam'
        'plez.com%2Fprogramming%2Fpython%2Dasyncio%2Dtutorial&amp;rut=305613caa08d4cac63353ad75801512996890191db250fcccc6d2ce606f'
        '0e856">Learn <b>Python</b> <b>AsyncIO</b> with our beginner-friendly <b>tutorial</b>. Master asynchronous programming, c'
        'oroutines, and more. Start coding efficiently!</a>\n<div class="clear"></div>\n</div>\n</div>\n<div class="result results_li'
        'nks results_links_deep web-result ">\n<div class="links_main links_deep result__body"> <!-- This is the visible part -->\n'
        '<h2 class="result__title">\n<a rel="nofollow" class="result__a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fdocs.python.'
        'org%2F3%2Flibrary%2Fasyncio.html&amp;rut=0dd4928214a95b01398693176962e7e38a7ba1a04d597a5bd4e7f444da638fdd">asyncio — Asy'
        'nchronous I/O — Python 3.14.7 documentation</a>\n</h2>\n<div class="result__extras">\n<div class="result__extras__url">\n<sp'
        'an class="result__icon">\n<a rel="nofollow" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2F'
        'asyncio.html&amp;rut=0dd4928214a95b01398693176962e7e38a7ba1a04d597a5bd4e7f444da638fdd">\n<img class="result__icon__img" w'
        'idth="16" height="16" alt="" src="//external-content.duckduckgo.com/ip3/docs.python.org.ico" name="i15">\n</a>\n</span>\n<a'
        ' class="result__url" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Fasyncio.html&amp;rut=0'
        'dd4928214a95b01398693176962e7e38a7ba1a04d597a5bd4e7f444da638fdd">\ndocs.python.org/3/library/asyncio.html\n</a>\n</div>\n</d'
        'iv>\n<a class="result__snippet" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Fasyncio.html'
        '&amp;rut=0dd4928214a95b01398693176962e7e38a7ba1a04d597a5bd4e7f444da638fdd"><b>asyncio</b> is a library to write concurre'
        'nt code using the async/await syntax. <b>asyncio</b> is used as a foundation for multiple <b>Python</b> asynchronous fra'
        'meworks that provide high-performance network and web-servers, database connection libraries, distributed task queues, e'
        'tc. <b>asyncio</b> is often a perfect fit for IO-bound and high-level structured network code.</a>\n<div class="clear"></'
        'div>\n</div>\n</div>\n<div class="result results_links results_links_deep web-result ">\n<div class="links_main links_deep r'
        'esult__body"> <!-- This is the visible part -->\n<h2 class="result__title">\n<a rel="nofollow" class="result__a" href="//d'
        'uckduckgo.com/l/?uddg=https%3A%2F%2Fwww.datacamp.com%2Ftutorial%2Fpython%2Dasync%2Dprogramming&amp;rut=78ed5b96d67e7dfb4'
        '457af05a6ffce3312d77d33e8caab12f6b1b32b05a543ac">Python Async Programming: The Complete Guide - DataCamp</a>\n</h2>\n<div '
        'class="result__extras">\n<div class="result__extras__url">\n<span class="result__icon">\n<a rel="nofollow" href="//duckduck'
        'go.com/l/?uddg=https%3A%2F%2Fwww.datacamp.com%2Ftutorial%2Fpython%2Dasync%2Dprogramming&amp;rut=78ed5b96d67e7dfb4457af05'
        'a6ffce3312d77d33e8caab12f6b1b32b05a543ac">\n<img class="result__icon__img" width="16" height="16" alt="" src="//external-'
        'content.duckduckgo.com/ip3/www.datacamp.com.ico" name="i15">\n</a>\n</span>\n<a class="result__url" href="//duckduckgo.com/'
        'l/?uddg=https%3A%2F%2Fwww.datacamp.com%2Ftutorial%2Fpython%2Dasync%2Dprogramming&amp;rut=78ed5b96d67e7dfb4457af05a6ffce3'
        '312d77d33e8caab12f6b1b32b05a543ac">\nwww.datacamp.com/tutorial/python-async-programming\n</a>\n<span>&nbsp; &nbsp; 2025-12-'
        '08T00:00:00.0000000</span>\n</div>\n</div>\n<a class="result__snippet" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fwww.dat'
        'acamp.com%2Ftutorial%2Fpython%2Dasync%2Dprogramming&amp;rut=78ed5b96d67e7dfb4457af05a6ffce3312d77d33e8caab12f6b1b32b05a5'
        '43ac">Speed up your code with <b>Python</b> async programming. A step-by-step guide to <b>asyncio</b>, concurrency, effi'
        'cient HTTP requests, and database integration.</a>\n<div class="clear"></div>\n</div>\n</div></div></div></body></html>'
    ),
    'ddg-lite': (
        'text/html; charset=UTF-8',
        '<!DOCTYPE html><html><head><title>DuckDuckGo</title></head><body><table border="0"><tr class="result-sponsored">\n<!-- Sp'
        'onsored result with counter -->\n<td valign="top">\n1.&nbsp;\n</td>\n<td>\n<a rel="nofollow" href="//duckduckgo.com/l/?uddg=h'
        'ttps%3A%2F%2Fduckduckgo.com%2Fy.js%3Fad_domain%3Dudemy.com%26ad_provider%3Dbingv7aa%26ad_type%3Dtxad%26click_metadata%3D'
        'ATdhY_LN6Zt2y9LcP3PZvFVrigcelaWlt_gAMTY10WXj7exmndyuRw6cc9UYHyCFDrwJvdgJ9LZIQ1Zu5PG68ljUYNmb_GBdt6iGSWQJoQgpTT4sQ_T8Tq2g'
        'HHnuqV5sJs%252D3F5tJIouEsraIYL6oS4KS5gNIlNSVzWt3tSvMxJI.Cr%252DlN1LYMUsi%252DK_esI7cXw%26rut%3Ddf292518af23a811c76a51a61'
        '301a7a90f14ec3fc8feed6bbe4a81afc59f8e22%26u3%3Dhttps%253A%252F%252Fwww.bing.com%252Faclick%253Fld%253De8EoR03ghZdHPA1Nw3'
        '9D%252DOXzVUCUyf1YaP6MQpyAzjA5pSMg3gViz1lrW6UM3c8mKvOUgvuJFMwR2xWL4gOQRHuGObKGMRFF4bQppYnpGG1%252DOwO8uh%252DwxqaqVIzMrY'
        '7WJ1iKXbexD_uLM2g1ap_1oFjE_mmUczNJk6jsaYOX4PSTNiOSAss_8YWwFWVLZG9TN0pYKBhwG%252DB5o09uPhQ5J3wD2JVMw%2526u%253DaHR0cHMlM2'
        'ElMmYlMmZ3d3cudWRlbXkuY29tJTJmY291cnNlJTJmc3VwZXJjaGFyZ2VkLXdlYi1zY3JhcGluZy13aXRoLWFzeW5jaW8tYW5kLXB5dGhvbiUyZiUzZnV0bV'
        '9jYW1wYWlnbiUzZEJHLVNlYXJjaF9EU0FfQWxwaGFfUHJvZl9sYS5FTl9jYy5ST1ctRW5nbGlzaCUyNnV0bV9zb3VyY2UlM2RiaW5nJTI2dXRtX21lZGl1bS'
        'UzZHBhaWQtc2VhcmNoJTI2cG9ydGZvbGlvJTNkQmluZy1ST1ctRW5nbGlzaCUyNnV0bV9hdWRpZW5jZSUzZG14JTI2dXRtX3RhY3RpYyUzZG5iJTI2dXRtX3'
        'Rlcm0lM2RfLl9hZ18xMzE3MjE3MzE4NjQ5NjA0Xy5fYWRfXy5fa3dfRGF0YSUyNTIwU2NpZW5jZSUyNnV0bV9jb250ZW50JTNkcyUyNmZ1bm5lbCUzZCUyNn'
        'Rlc3QlM2QlMjZ1dG1fY2FtcGFpZ25faWQlM2Q2Mzg1OTYyMjglMjZtc2Nsa2lkJTNkMGFjODE5MmM2OWMzMTgzNWEwOTI3Mzk5ZmE3YjM4MmI%2526rlid%2'
        '53D0ac8192c69c31835a0927399fa7b382b%26vqd%3D4%2D136869678818319787332840225433968722920%26iurl%3D%257B1%257DIG%253D39BAA'
        '759038A4ABBABF84EE3E9B33AC2%2526CID%253D26A4E6931219630D02F1F14D133F6279%2526ID%253DDevEx%252C5037.1&amp;rut=3007b8c2aa2'
        '622d74cbdb6acd42b578665bd3985c1596c2abcce841498bc77c1" class="result-link">Python Asyncio Tutorial - Learn Asynchronous '
        'Web Scraping with Python</a>\n(Sponsored link - <a href="https://duckduckgo.com/duckduckgo-help-pages/company/ads-by-micr'
        'osoft-on-duckduckgo-private-search/" rel="nofollow" class="result-link">more info</a>)\n</td>\n</tr>\n<tr class="result-spo'
        'nsored">\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td class="result-snippet">\nMaster Data Science and become a pro. Start today and i'
        'mprove your skills. Find the right instructor for you. Choose from many topics, skill levels, and languages.\n</td>\n</tr>'
        '\n<tr class="result-sponsored">\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td>\n<span class="link-text">udemy.com</span>\n</td>\n</tr>\n<tr'
        '>\n<td>&nbsp;</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td valign="top">\n2.&nbsp;\n</td>\n<td>\n<a rel="nofollow" href="//duckduckgo.'
        'com/l/?uddg=https%3A%2F%2Frealpython.com%2Fasync%2Dio%2Dpython%2F&amp;rut=3f1810d12af587f4db70c3cfee586ef362febe0b6f16ad'
        'b20db167bb14516cd3" class="result-link">Python\'s asyncio: A Hands-On Walkthrough - Real Python</a>\n</td>\n</tr>\n<tr>\n<td>'
        '&nbsp;&nbsp;&nbsp;</td>\n<td class="result-snippet">\n<b>Python\'s</b> <b>asyncio</b> library enables you to write concurre'
        'nt code using the async and await keywords. The core building blocks of <b>async</b> <b>I/O</b> in <b>Python</b> are awa'
        'itable objects—most often coroutines—that an event loop schedules and executes asynchronously. This programming model le'
        "ts you efficiently manage multiple I/O-bound tasks within a single thread of execution. In this <b>tutorial</b>, you'll "
        '...\n</td>\n</tr>\n<tr>\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td>\n<span class="link-text">realpython.com/async-io-python/</span>\n&nb'
        'sp;&nbsp;&nbsp;\n<span class="timestamp">2025-07-30T00:00:00.0000000</span>\n</td>\n</tr>\n<tr>\n<td>&nbsp;</td>\n<td>&nbsp;</'
        'td>\n</tr>\n<tr>\n<td valign="top">\n3.&nbsp;\n</td>\n<td>\n<a rel="nofollow" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fwww.'
        'geeksforgeeks.org%2Fpython%2Fasyncio%2Din%2Dpython%2F&amp;rut=09c2e9caf0f59f9e8b117f5bd998310aac9ccd4fe7faf36aa5190d4819'
        '2ea381" class="result-link">asyncio in Python - GeeksforGeeks</a>\n</td>\n</tr>\n<tr>\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td class'
        '="result-snippet">\n<b>Asyncio</b> is used as a foundation for multiple <b>Python</b> asynchronous frameworks that provid'
        'e high-performance network and web servers, database connection libraries, distributed task queues, etc Asynchronous Pro'
        "gramming with <b>Asyncio</b> in <b>Python</b> In the example below, we'll create a function and make it asynchronous usi"
        'ng the async keyword.\n</td>\n</tr>\n<tr>\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td>\n<span class="link-text">www.geeksforgeeks.org/py'
        'thon/asyncio-in-python/</span>\n&nbsp;&nbsp;&nbsp;\n<span class="timestamp">2025-07-23T00:00:00.0000000</span>\n</td>\n</tr>'
        '\n<tr>\n<td>&nbsp;</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td valign="top">\n4.&nbsp;\n</td>\n<td>\n<a rel="nofollow" href="//duckduc'
        'kgo.com/l/?uddg=https%3A%2F%2Fcodesamplez.com%2Fprogramming%2Fpython%2Dasyncio%2Dtutorial&amp;rut=305613caa08d4cac63353a'
        'd75801512996890191db250fcccc6d2ce606f0e856" class="result-link">Python AsyncIO Tutorial: A Comprehensive Guide To Async '
        'Python</a>\n</td>\n</tr>\n<tr>\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td class="result-snippet">\nLearn <b>Python</b> <b>AsyncIO</b> w'
        'ith our beginner-friendly <b>tutorial</b>. Master asynchronous programming, coroutines, and more. Start coding efficient'
        'ly!\n</td>\n</tr>\n<tr>\n<td>&nbsp;&nbsp;&nbsp;</td>\n<td>\n<span class="link-text">codesamplez.com/programming/python-asyncio'
        '-tutorial</span>\n&nbsp;&nbsp;&nbsp;\n<span class="timestamp">2025-02-10T00:00:00.0000000</span>\n</td>\n</tr>\n<tr>\n<td>&nbs'
        'p;</td>\n<td>&nbsp;</td>\n</tr></table></body></html>'
    ),
    'mwmbl': (
        'application/json',
        '[{"url": "https://docs.python.org/fr/3.8/library/asyncio.html", "title": [{"value": "asyncio", "is_bold": true}, {"value'
        '": " \\u2014 Entr\\u00e9es/Sorties asynchrones \\u2014 Documentation ", "is_bold": false}, {"value": "Python", "is_bold": t'
        'rue}, {"value": " 3.8\\u2026", "is_bold": false}], "extract": [], "source": "mwmbl"}, {"url": "https://docs.python.org/fr'
        '/3.7/library/asyncio.html", "title": [{"value": "asyncio", "is_bold": true}, {"value": " \\u2014 Entr\\u00e9es/Sorties asy'
        'nchrones \\u2014 Documentation ", "is_bold": false}, {"value": "Python", "is_bold": true}, {"value": " 3.7\\u2026", "is_bo'
        'ld": false}], "extract": [], "source": "mwmbl"}, {"url": "https://docs.python.org/fr/3.9/library/asyncio.html", "title":'
        ' [{"value": "asyncio", "is_bold": true}, {"value": " \\u2014 Entr\\u00e9es/Sorties asynchrones \\u2014 Documentation ", "is'
        '_bold": false}, {"value": "Python", "is_bold": true}, {"value": " 3.9\\u2026", "is_bold": false}], "extract": [], "source'
        '": "mwmbl"}]'
    ),
    'marginalia': (
        'application/json',
        '{"license": "CC-BY-NC-SA 4.0", "page": 1, "pages": 11, "query": "python asyncio tutorial", "results": [{"url": "https://'
        'docs.python.org/3/library/asyncio.html", "title": "asyncio \\u2014 Asynchronous I/O \\u2014 Python 3.14.5 documentation", '
        '"description": "m asyncio asyncio REPL _, Use, await, directly instead of, asyncio.run. Type, help, copyright, credits, '
        'or, license // Reference High-level APIs Low-level APIs Guides and Tutorials Note The source code for asyncio can be fou'
        'nd in. Lib/asyncio/", "quality": 3.979742121933176, "format": "html", "resultsFromDomain": 13, "details": [[]]}, {"url":'
        ' "https://discuss.python.org/t/how-open-a-unix-domain-socket-with-asyncio/55399", "title": "How open a Unix domain socke'
        't with asyncio? - Python Help - Discussions on Python.org", "description": "asyncio streams. There is explaination on ho'
        'w open a connection/stream for TCP, but nothing for Unix domain socket Ive tried // asyncio is used as a foundation for '
        'multiple Python asynchronous frameworks that provide high-performance n, 1 Like", "quality": 4.0030221550859855, "format'
        '": "html", "resultsFromDomain": 23, "details": [[]]}, {"url": "https://docs.python.org/3.14/library/asyncio.html", "titl'
        'e": "asyncio \\u2014 Asynchronous I/O \\u2014 Python 3.14.7 documentation", "description": "m asyncio asyncio REPL _, Use,'
        ' await, directly instead of, asyncio.run. Type, help, copyright, credits, or, license, for // Reference High-level APIs '
        'Introspection APIs Low-level APIs Guides and Tutorials Note The source code for asyncio can be...", "quality": 4.0031484'
        '58537789, "format": "html", "resultsFromDomain": 13, "details": [[]]}]}'
    ),
    'openalex': (
        'application/json',
        '{"meta": {"count": 191222, "page": 1, "per_page": 2}, "results": [{"id": "https://openalex.org/W4389984066", "doi": "htt'
        'ps://doi.org/10.48550/arxiv.2312.10997", "title": "Retrieval-Augmented Generation for Large Language Models: A Survey", '
        '"display_name": "Retrieval-Augmented Generation for Large Language Models: A Survey", "publication_year": 2023, "publica'
        'tion_date": "2023-12-18", "primary_location": {"landing_page_url": "http://arxiv.org/abs/2312.10997", "source": {"displa'
        'y_name": "arXiv (Cornell University)"}}, "type": "preprint", "open_access": {"is_oa": true, "oa_status": "green", "oa_ur'
        'l": "https://arxiv.org/pdf/2312.10997", "any_repository_has_fulltext": true}, "authorships": [{"author": {"display_name"'
        ': "Yunfan Gao"}}, {"author": {"display_name": "Yun Xiong"}}, {"author": {"display_name": "Xinyu Gao"}}, {"author": {"dis'
        'play_name": "Kangxiang Jia"}}], "cited_by_count": 749, "abstract_inverted_index": {"Large": [0], "Language": [1], "Model'
        's": [2], "(LLMs)": [3], "showcase": [4], "impressive": [5], "capabilities": [6], "but": [7], "encounter": [8], "challeng'
        'es": [9], "like": [10], "hallucination,": [11], "outdated": [12], "knowledge,": [13], "and": [14, 38], "non-transparent,'
        '": [15], "untraceable": [16], "reasoning": [17], "processes.": [18], "Retrieval-Augmented": [19], "Generation": [20], "('
        'RAG)": [21], "has": [22], "emerged": [23], "as": [24], "a": [25], "promising": [26], "solution": [27], "by": [28], "inco'
        'rporating": [29], "knowledge": [30], "from": [31], "external": [32], "databases.": [33], "This": [34], "enhances": [35],'
        ' "the": [36, 41], "accuracy": [37], "credibility": [39], "of": [40], "generation,": [42], "particularly": [43], "for": ['
        '44]}}, {"id": "https://openalex.org/W4389519118", "doi": "https://doi.org/10.18653/v1/2023.emnlp-main.495", "title": "Ac'
        'tive Retrieval Augmented Generation", "display_name": "Active Retrieval Augmented Generation", "publication_year": 2023,'
        ' "publication_date": "2023-01-01", "primary_location": {"landing_page_url": "https://doi.org/10.18653/v1/2023.emnlp-main'
        '.495", "source": {"display_name": null}}, "type": "conference-paper", "open_access": {"is_oa": true, "oa_status": "gold"'
        ', "oa_url": "https://aclanthology.org/2023.emnlp-main.495.pdf", "any_repository_has_fulltext": null}, "authorships": [{"'
        'author": {"display_name": "Zhengbao Jiang"}}, {"author": {"display_name": "Frank F. Xu"}}, {"author": {"display_name": "'
        'Luyu Gao"}}, {"author": {"display_name": "Zhiqing Sun"}}], "cited_by_count": 449, "abstract_inverted_index": {"Zhengbao"'
        ': [0], "Jiang,": [1], "Frank": [2], "Xu,": [3], "Luyu": [4], "Gao,": [5], "Zhiqing": [6], "Sun,": [7], "Qian": [8], "Liu'
        ',": [9], "Jane": [10], "Dwivedi-Yu,": [11], "Yiming": [12], "Yang,": [13], "Jamie": [14], "Callan,": [15], "Graham": [16'
        '], "Neubig.": [17], "Proceedings": [18], "of": [19], "the": [20], "2023": [21], "Conference": [22], "on": [23], "Empiric'
        'al": [24], "Methods": [25], "in": [26], "Natural": [27], "Language": [28], "Processing.": [29], "2023.": [30]}}], "group'
        '_by": []}'
    ),
    'crossref': (
        'application/json',
        '{"status": "ok", "message-type": "work-list", "message": {"total-results": 1004100, "items": [{"DOI": "10.1002/978139437'
        '4717.ch03", "title": ["Retrieval\\u2010Augmented Generation"], "issued": {"date-parts": [[2026, 6, 30]]}, "container-titl'
        'e": ["Advanced Retrieval\\u2010Augmented Generation"], "type": "other", "URL": "https://doi.org/10.1002/9781394374717.ch0'
        '3", "is-referenced-by-count": 0, "publisher": "Wiley"}, {"DOI": "10.1002/9781394374717.ch07", "title": ["Graph\\u2010base'
        'd Retrieval\\u2010augmented Generation"], "issued": {"date-parts": [[2026, 6, 30]]}, "container-title": ["Advanced Retrie'
        'val\\u2010Augmented Generation"], "type": "other", "URL": "https://doi.org/10.1002/9781394374717.ch07", "is-referenced-by'
        '-count": 0, "publisher": "Wiley"}]}}'
    ),
    'pubmed-esearch': (
        'application/json',
        '{"header": {"type": "esearch", "version": "0.3"}, "esearchresult": {"count": "9366", "retmax": "5", "retstart": "0", "id'
        'list": ["42776539", "42772753", "42770282"]}}'
    ),
    'pubmed-esummary': (
        'application/json',
        '{"header": {"type": "esummary", "version": "0.3"}, "result": {"uids": ["42776539", "42772753", "42770282"], "42776539": '
        '{"uid": "42776539", "pubdate": "2026 Sep 23", "sortpubdate": "2026/09/23 00:00", "source": "JAMA Cardiol", "fulljournaln'
        'ame": "JAMA cardiology", "title": "Multidimensional Aging Trajectories Preceding Cardiovascular Events.", "authors": [{"'
        'name": "Phyo AZZ", "authtype": "Author", "clusterid": ""}, {"name": "Wu Z", "authtype": "Author", "clusterid": ""}, {"na'
        'me": "Tonkin AM", "authtype": "Author", "clusterid": ""}, {"name": "Vishwanath S", "authtype": "Author", "clusterid": ""'
        '}, {"name": "Espinoza SE", "authtype": "Author", "clusterid": ""}], "articleids": [{"idtype": "pubmed", "idtypen": 1, "v'
        'alue": "42776539"}, {"idtype": "doi", "idtypen": 3, "value": "10.1001/jamacardio.2026.3597"}, {"idtype": "pii", "idtypen'
        '": 4, "value": "2854524"}]}, "42772753": {"uid": "42772753", "pubdate": "2026 Sep 23", "sortpubdate": "2026/09/23 00:00"'
        ', "source": "Eur Heart J Cardiovasc Pharmacother", "fulljournalname": "European heart journal. Cardiovascular pharmacoth'
        'erapy", "title": "Coated or chewable Aspirin and a hybrid air pollution mitigation strategy in patients with atheroscler'
        'otic disease: Rationale and Design of the COATED-AIR Randomized Trial.", "authors": [{"name": "Bikdeli B", "authtype": "'
        'Author", "clusterid": ""}, {"name": "Talasaz AH", "authtype": "Author", "clusterid": ""}, {"name": "Bakhshandeh H", "aut'
        'htype": "Author", "clusterid": ""}, {"name": "Hassanvand MS", "authtype": "Author", "clusterid": ""}, {"name": "Kakavand'
        ' H", "authtype": "Author", "clusterid": ""}], "articleids": [{"idtype": "pubmed", "idtypen": 1, "value": "42772753"}, {"'
        'idtype": "doi", "idtypen": 3, "value": "10.1093/ehjcvp/pvag071"}, {"idtype": "pii", "idtypen": 4, "value": "8829042"}]},'
        ' "42770282": {"uid": "42770282", "pubdate": "2026 Oct", "sortpubdate": "2026/10/01 00:00", "source": "J Biochem Mol Toxi'
        'col", "fulljournalname": "Journal of biochemical and molecular toxicology", "title": "Eupatilin Alleviates Acute Myocard'
        'ial Ischemia-Reperfusion Injury in Rats via the Akt/GSK-3\\u03b2 Pathway by Targeting COXs.", "authors": [{"name": "Guo M'
        '", "authtype": "Author", "clusterid": ""}, {"name": "Li Q", "authtype": "Author", "clusterid": ""}, {"name": "Ji L", "au'
        'thtype": "Author", "clusterid": ""}], "articleids": [{"idtype": "pubmed", "idtypen": 1, "value": "42770282"}, {"idtype":'
        ' "pmc", "idtypen": 8, "value": "PMC13595355"}, {"idtype": "pmcid", "idtypen": 5, "value": "pmc-id: PMC13595355;"}, {"idt'
        'ype": "doi", "idtypen": 3, "value": "10.1002/jbt.71111"}]}}}'
    ),
    'github': (
        'application/json; charset=utf-8',
        '{"total_count": 715, "incomplete_results": false, "items": [{"full_name": "atlanhq/camelot", "html_url": "https://github'
        '.com/atlanhq/camelot", "description": "Camelot: PDF Table Extraction for Humans", "pushed_at": "2023-01-05T15:25:42Z", "'
        'updated_at": "2026-09-24T17:41:44Z", "stargazers_count": 3709, "language": "Python", "archived": true, "topics": ["extra'
        'ct", "for-humans", "pdf", "table"], "license": {"spdx_id": "NOASSERTION"}}, {"full_name": "xavctn/img2table", "html_url"'
        ': "https://github.com/xavctn/img2table", "description": "img2table is a table identification and extraction Python Libra'
        'ry for PDF and images, based on OpenCV image processing", "pushed_at": "2026-07-12T11:53:50Z", "updated_at": "2026-09-24'
        'T18:31:19Z", "stargazers_count": 901, "language": "Python", "archived": false, "topics": ["image-processing", "opencv", '
        '"python", "table-extraction"], "license": {"spdx_id": "MIT"}}]}'
    ),
    'stackexchange': (
        'application/json; charset=utf-8',
        '{"items": [{"tags": ["python", "sqlalchemy", "python-asyncio"], "is_answered": false, "answer_count": 1, "score": 0, "la'
        'st_activity_date": 1726321937, "creation_date": 1726304463, "question_id": 78984714, "link": "https://stackoverflow.com/'
        'questions/78984714/how-to-use-asyncio-gather-with-sqlalchemy-session-in-fastapi-and-the-workaround", "title": "How to us'
        'e asyncio gather with sqlalchemy session in FastAPI and the workaround"}, {"tags": ["python", "python-3.x", "python-asyn'
        'cio", "python-internals"], "is_answered": true, "answer_count": 6, "score": 390, "last_activity_date": 1770059716, "crea'
        'tion_date": 1519724891, "question_id": 49005651, "link": "https://stackoverflow.com/questions/49005651/how-does-asyncio-'
        'actually-work", "title": "How does asyncio actually work?"}], "has_more": true, "quota_max": 300, "quota_remaining": 290'
        '}'
    ),
    'hackernews': (
        'application/json',
        '{"hits": [{"objectID": "27016630", "title": "Hosting SQLite databases on GitHub Pages or any static file hoster", "url":'
        ' "https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/", "author": "phiresky", "points": 1812,'
        ' "num_comments": 244, "created_at": "2021-05-02T16:43:15Z", "created_at_i": 1619973795, "story_id": 27016630}, {"objectI'
        'D": "31318708", "title": "I\'m all-in on server-side SQLite", "url": "https://fly.io/blog/all-in-on-sqlite-litestream/", '
        '"author": "dpeck", "points": 1353, "num_comments": 404, "created_at": "2022-05-09T19:35:41Z", "created_at_i": 1652124941'
        ', "story_id": 31318708}], "nbHits": 54054, "page": 0}'
    ),
    'pypi': (
        'application/json',
        '{"info": {"name": "httpx", "version": "0.28.1", "summary": "The next generation HTTP client.", "home_page": null, "proje'
        'ct_urls": {"Changelog": "https://github.com/encode/httpx/blob/master/CHANGELOG.md", "Documentation": "https://www.python'
        '-httpx.org", "Homepage": "https://github.com/encode/httpx", "Source": "https://github.com/encode/httpx"}, "package_url":'
        ' "https://pypi.org/project/httpx/", "requires_python": ">=3.8", "license": "BSD-3-Clause", "license_expression": null, "'
        'author": null}, "urls": [{"filename": "httpx-0.28.1-py3-none-any.whl", "upload_time": "2024-12-06T15:37:21", "upload_tim'
        'e_iso_8601": "2024-12-06T15:37:21.509172Z", "packagetype": "bdist_wheel"}], "releases": {}}'
    ),
    'npm': (
        'application/json',
        '{"objects": [{"downloads": {"monthly": 270992176, "weekly": 55320052}, "updated": "2026-09-22T12:13:23.337Z", "package":'
        ' {"name": "marked", "version": "18.0.14", "description": "A markdown parser built for speed", "date": "2026-09-22T06:09:'
        '15.277Z", "links": {"homepage": "https://marked.js.org", "repository": "git+https://github.com/markedjs/marked.git", "bu'
        'gs": "https://github.com/markedjs/marked/issues", "npm": "https://www.npmjs.com/package/marked"}, "keywords": ["markdown'
        '", "markup", "html"]}}, {"downloads": {"monthly": 108088286, "weekly": 20702593}, "updated": "2026-09-22T12:17:09.606Z",'
        ' "package": {"name": "markdown-it", "version": "15.0.2", "description": "Markdown-it - modern pluggable markdown parser.'
        '", "date": "2026-09-11T04:04:18.194Z", "links": {"homepage": "https://github.com/markdown-it/markdown-it#readme", "repos'
        'itory": "git+https://github.com/markdown-it/markdown-it.git", "bugs": "https://github.com/markdown-it/markdown-it/issues'
        '", "npm": "https://www.npmjs.com/package/markdown-it"}, "keywords": ["markdown", "parser", "commonmark", "markdown-it", '
        '"markdown-it-plugin"]}}], "total": 2387028}'
    ),
    'crates': (
        'application/json',
        '{"crates": [{"id": "cdk-http-client", "name": "cdk-http-client", "description": "HTTP client abstraction for CDK", "upda'
        'ted_at": "2026-09-18T08:45:38.860534Z", "downloads": 17093, "max_version": "0.18.1", "max_stable_version": "0.18.1", "re'
        'pository": "https://github.com/cashubtc/cdk.git"}, {"id": "http-client", "name": "http-client", "description": "Types an'
        'd traits for http clients.", "updated_at": "2022-06-20T20:34:06.027569Z", "downloads": 7815646, "max_version": "6.5.3", '
        '"max_stable_version": "6.5.3", "repository": "https://github.com/http-rs/http-client"}], "meta": {"total": 2}}'
    ),
    'wikipedia': (
        'application/json; charset=utf-8',
        '{"batchcomplete": true, "query": {"pages": [{"pageid": 41131139, "ns": 0, "title": "Identity fusion", "index": 1, "extra'
        'ct": "Identity fusion, a psychological construct rooted in social psychology and cognitive anthropology, is a form of al'
        'ignment with groups in which members experience a visceral sense of oneness with the group. The construct relies on a di'
        'stinction between the personal self (characteristics that make someone a unique person, such as height, age, or personal'
        'ity) and the social self (characteristics that align the person with various groups, such as common nationalities, inter'
        'ests, or motivations).", "touched": "2026-09-23T22:23:02Z", "fullurl": "https://en.wikipedia.org/wiki/Identity_fusion"},'
        ' {"pageid": 2169464, "ns": 0, "title": "Dry as a Bone", "index": 2, "extract": "Dry as a Bone is the second and final EP'
        ' by the American rock band Green River. It was released in June 1987 through Sub Pop Records.", "touched": "2026-09-22T1'
        '1:38:33Z", "fullurl": "https://en.wikipedia.org/wiki/Dry_as_a_Bone"}, {"pageid": 79693418, "ns": 0, "title": "Los Thutha'
        'naka", "index": 3, "extract": "Los Thuthanaka is the debut studio album by the American duo Los Thuthanaka, consisting o'
        'f siblings Chuquimamani-Condori and Joshua Chuquimia Crampton. The album was self-released on March 22, 2025, as a surpr'
        'ise release, exclusively on Bandcamp.", "touched": "2026-09-22T11:53:54Z", "fullurl": "https://en.wikipedia.org/wiki/Los'
        '_Thuthanaka"}]}}'
    ),
    'wikidata': (
        'application/json; charset=utf-8',
        '{"searchinfo": {"search": "Marie Curie"}, "search": [{"id": "Q7186", "label": "Marie Curie", "description": "Polish-born'
        ' French physicist and chemist (1867\\u20131934)", "concepturi": "http://www.wikidata.org/entity/Q7186", "url": "//www.wik'
        'idata.org/wiki/Q7186"}, {"id": "Q114939443", "label": "Marie Curie", "description": "2022 Czech book edition", "conceptu'
        'ri": "http://www.wikidata.org/entity/Q114939443", "url": "//www.wikidata.org/wiki/Q114939443"}], "success": 1}'
    ),
    'openlibrary': (
        'application/json',
        '{"numFound": 277, "start": 0, "docs": [{"author_name": ["Frank Herbert"], "edition_count": 155, "first_publish_year": 19'
        '65, "isbn": ["9780441013593", "9780340839935", "044100590X"], "key": "/works/OL893414W", "title": "Dune"}, {"author_name'
        '": ["Frank Herbert"], "edition_count": 101, "first_publish_year": 1969, "isbn": ["8418037679", "9788466372015", "8373017'
        '259"], "key": "/works/OL893461W", "title": "Dune Messiah"}]}'
    ),
    'nominatim': (
        'application/json; charset=utf-8',
        '[{"place_id": 97838275, "licence": "Data \\u00a9 OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright", "osm_ty'
        'pe": "way", "osm_id": 5013364, "lat": "48.8582599", "lon": "2.2945006", "category": "man_made", "type": "tower", "place_'
        'rank": 30, "importance": 0.6205937724353116, "addresstype": "man_made", "name": "Eiffel Tower", "display_name": "Eiffel '
        'Tower, 5, Avenue Anatole France, Quartier du Gros-Caillou, 7th Arrondissement, Paris, Ile-de-France, Metropolitan France'
        ', 75007, France", "boundingbox": ["48.8574753", "48.8590453", "2.2933119", "2.2956897"]}, {"place_id": 376463881, "licen'
        'ce": "Data \\u00a9 OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright", "osm_type": "node", "osm_id": 2689315'
        '641, "lat": "51.3336000", "lon": "-116.2350000", "category": "natural", "type": "peak", "place_rank": 18, "importance": '
        '0.16000999999999999, "addresstype": "peak", "name": "Eiffel Tower", "display_name": "Eiffel Tower, Improvement District '
        'No. 9, Alberta, Canada", "boundingbox": ["51.3335500", "51.3336500", "-116.2350500", "-116.2349500"]}]'
    ),
    'youtube': (
        'text/html; charset=utf-8',
        '<!DOCTYPE html><html lang="en"><head><title>python asyncio tutorial - YouTube</title></head><body><script nonce="x">var '
        'ytInitialData = {"contents": {"twoColumnSearchResultsRenderer": {"primaryContents": {"sectionListRenderer": {"contents":'
        ' [{"itemSectionRenderer": {"contents": [{"videoRenderer": {"videoId": "Qb9s3UiMSTA", "title": {"runs": [{"text": "Asynci'
        'o in Python - Full Tutorial"}]}, "longBylineText": {"runs": [{"text": "Tech With Tim"}]}, "ownerText": {"runs": [{"text"'
        ': "Tech With Tim"}]}, "publishedTimeText": {"simpleText": "2 years ago"}, "lengthText": {"accessibility": {"accessibilit'
        'yData": {"label": "24 minutes, 59 seconds"}}, "simpleText": "24:59"}, "viewCountText": {"simpleText": "378,402 views"}, '
        '"detailedMetadataSnippets": [{"snippetText": {"runs": [{"text": "Asynchronous programming allows our code to be more eff'
        'icient by doing multiple things at once without any unnecessary\\u00a0..."}]}}]}}, {"videoRenderer": {"videoId": "oAkLSJN'
        'r5zY", "title": {"runs": [{"text": "Python Tutorial: AsyncIO - Complete Guide to Asynchronous Programming with Animation'
        's"}]}, "longBylineText": {"runs": [{"text": "Corey Schafer"}]}, "ownerText": {"runs": [{"text": "Corey Schafer"}]}, "pub'
        'lishedTimeText": {"simpleText": "1 year ago"}, "lengthText": {"accessibility": {"accessibilityData": {"label": "1 hour, '
        '42 minutes, 41 seconds"}}, "simpleText": "1:42:41"}, "viewCountText": {"simpleText": "183,553 views"}, "detailedMetadata'
        'Snippets": [{"snippetText": {"runs": [{"text": "In this video, we\'ll be learning all about "}, {"text": "AsyncIO"}, {"te'
        'xt": " in "}, {"text": "Python"}, {"text": " and how to write asynchronous code using the async/await syntax."}]}}]}}]}}'
        ']}}}}, "estimatedResults": "1000"};</script></body></html>'
    ),
    'reddit': (
        'application/atom+xml; charset=UTF-8',
        '<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrs'
        's/"><category term=" reddit.com" label="r/ reddit.com"/><updated>2026-09-24T22:06:00+00:00</updated><id>/search.rss?q=sq'
        'lite+fts5&amp;limit=10</id><link rel="self" href="https://www.reddit.com/search.rss?q=sqlite+fts5&amp;limit=10" type="ap'
        'plication/atom+xml" /><link rel="alternate" href="https://www.reddit.com/search?q=sqlite+fts5&amp;limit=10" type="text/h'
        'tml" /><title>reddit.com: search results - sqlite fts5</title><entry><author><name>/u/Barnet1123</name><uri>https://www.'
        'reddit.com/user/Barnet1123</uri></author><category term="hermesagent" label="r/hermesagent"/><content type="html">&lt;!-'
        '- SC_OFF --&gt;&lt;div class=&quot;md&quot;&gt;&lt;p&gt;Hi,&lt;/p&gt; &lt;p&gt;I built a custom Document Structuring Ski'
        'll for Hermes Agent because running massive tech manuals on local hardware was completely blowing up my context window ('
        'and I’m doing this on a budget).&lt;/p&gt; &lt;p&gt;The main goal is to structurally parse large PDFs/DOCXs, drastically'
        ' reduce LLM token consumption, and improve retrieval efficiency. I went with a lightweight SQLite FTS5 backend instead o'
        'f a heavy vector DB to keep it fast and simple.&lt;/p&gt; &lt;p&gt;Currently, I&amp;#39;ve only tested this in a l</cont'
        'ent><id>t3_1u9zkkj</id><link href="https://www.reddit.com/r/hermesagent/comments/1u9zkkj/built_a_local_pdfdocx_parsing_s'
        'kill_for_hermes/" /><updated>2026-06-19T11:34:47+00:00</updated><published>2026-06-19T11:34:47+00:00</published><title>B'
        'uilt a Local PDF/DOCX Parsing Skill for Hermes: Dropped Context from 2.7M to 2.2K Tokens (SQLite FTS5)</title></entry><e'
        'ntry><author><name>/u/UnderstandingEither4</name><uri>https://www.reddit.com/user/UnderstandingEither4</uri></author><ca'
        'tegory term="golang" label="r/golang"/><content type="html">&lt;!-- SC_OFF --&gt;&lt;div class=&quot;md&quot;&gt;&lt;p&g'
        't;I looked for an embeddable hybrid search library in Go for a project. Something I could import, call Index(), call Sea'
        'rch(), and not think about again.&lt;br/&gt; Didn&amp;#39;t find one. Spent 5 months building it instead.&lt;/p&gt; &lt;'
        'p&gt;The storage layer is hand-written WAL, MemTable, SSTables, Bloom filters. BM25 over actual posting lists, not a ful'
        'l scan. Dense vectors via ONNX, fused with BM25 using weighted RRF. The hybrid mode is the point.&lt;/p&gt; &lt;p&gt;Har'
        'dest bug: BM25 scores were being computed and silently ignor</content><id>t3_1u6anlm</id><link href="https://www.reddit.'
        'com/r/golang/comments/1u6anlm/sqlite_fts5_gets_0625_recall10_on_ms_marco_i_got/" /><updated>2026-06-15T08:29:15+00:00</u'
        'pdated><published>2026-06-15T08:29:15+00:00</published><title>SQLite FTS5 gets 0.625 Recall@10 on MS MARCO. I got 0.906 '
        "with a Go library that embeds the same way. Here's what I built.</title></entry><entry><author><name>/u/Impressive_Tower"
        '_550</name><uri>https://www.reddit.com/user/Impressive_Tower_550</uri></author><category term="LocalLLaMA" label="r/Loca'
        'lLLaMA"/><content type="html">&lt;!-- SC_OFF --&gt;&lt;div class=&quot;md&quot;&gt;&lt;p&gt;A few months ago I posted ab'
        'out classifying 3.5M US patents with Nemotron 9B on a single RTX 5090. This is a follow-up on the data-engineering side.'
        ' Disclosure up front: I&amp;#39;m a patent lawyer who started coding in Dec 2025, and I build and run the site&lt;/p&gt;'
        ' &lt;p&gt;mentioned at the end (free, no signup, no ads — it&amp;#39;s a hobby project).&lt;/p&gt; &lt;p&gt;Things that '
        'might save you time:&lt;/p&gt; &lt;p&gt;- PatentsView moved to the USPTO Open Data Portal in March 2026. The old S3 down'
        'load links are dead. Abstracts</content><id>t3_1utl6r5</id><link href="https://www.reddit.com/r/LocalLLaMA/comments/1utl'
        '6r5/followup_what_i_learned_scaling_a_sqlitefts5/" /><updated>2026-07-11T14:11:53+00:00</updated><published>2026-07-11T1'
        '4:11:53+00:00</published><title>Follow-up: what I learned scaling a SQLite/FTS5 patent database from 3.5M to 5.36M recor'
        'ds</title></entry></feed>'
    ),
    'cc-collinfo': (
        'application/json',
        '[{"id": "CC-MAIN-2026-39", "name": "September 2026 Index", "timegate": "https://index.commoncrawl.org/CC-MAIN-2026-39/",'
        ' "cdx-api": "https://index.commoncrawl.org/CC-MAIN-2026-39-index", "from": "2026-09-04T13:16:03", "to": "2026-09-17T05:5'
        '9:21"}, {"id": "CC-MAIN-2026-34", "name": "August 2026 Index", "timegate": "https://index.commoncrawl.org/CC-MAIN-2026-3'
        '4/", "cdx-api": "https://index.commoncrawl.org/CC-MAIN-2026-34-index", "from": "2026-08-07T10:18:45", "to": "2026-08-20T'
        '01:52:41"}]'
    ),
}
